name: build

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: go format
        run: gofmt -s -w . && git diff --exit-code

      - name: go tidy
        run: go mod tidy && git diff --exit-code

      - name: go mod
        run: go mod download

      - name: go build
        run: go build -v ./...

      - name: go test
        run: go test -v -race -timeout=60s -shuffle=on -coverprofile=profile.cov ./...

      - name: submit coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: profile.cov
          fail_ci_if_error: false